---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${NAME}
  template:
    metadata:
      labels:
        app: ${NAME}
    spec:
      containers:
        - name: ${NAME}
          image: ${IMAGE}
          ports:
            - name: api-port
              containerPort: ${PORT}
              #hostPort: ${PORT}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: api-port
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: api-port
            initialDelaySeconds: 5
            failureThreshold: 10
            periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
spec:
  selector:
    app: ${NAME}
  type: ClusterIP
  ports:
    - name: http
      port: ${PORT}
      targetPort: ${PORT}