apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: validation-v1
  namespace: tap-dev
  description: validation api
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=validation-v1'
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: yelb
  providesApis:
    - tap-dev/validation-v1