apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: training-sample-validation
spec:
  gitImplementation: go-git
  ignore: '!.git'
  interval: 1m0s
  timeout: 20s
  secretRef:
    name: gitlab-metaage-auth
  ref:
    branch: master
  url: https://gitlab.sysage.com.tw/training/sample/validation.git