apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: validation-v1
  namespace: tap-dev
  labels:
    app.kubernetes.io/part-of: validation-v1
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: gitops_ssh_secret
      value: gitlab-auth
    - name: dockerfile
      value: ./Dockerfile
    - name: debug
      value: "false"
    - name: api_descriptor
      value:
        type: openapi
        location:
          path: "/v3/api-docs"
        system: yelb
        owner: guest
        description: validation api demo
  #  resources:
  #    limits:
  #      cpu: 1000m
  #      memory: 536870912
  #    requests:
  #      cpu: 100m
  #      memory: 536870912
  source:
    git:
      ref:
        branch: master
      url: https://gitlab.metaage.tech/training/sample/validation.git
