apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: validation-v1
  namespace: default
  labels:
    app.kubernetes.io/part-of: validation-v1
    apps.tanzu.vmware.com/workload-type: web
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: gitops_ssh_secret
      value: gitlab-metaage-auth
    - name: dockerfile
      value: ./Dockerfile
    - name: debug
      value: "false"
  #  resources:
  #    limits:
  #      cpu: 1000m
  #      memory: 536870912
  #    requests:
  #      cpu: 100m
  #      memory: 536870912
  source:
    git:
      ref:
        branch: master
      url: https://github.com/metaage-vmware/validation.git
