apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: validation-v1
  namespace: default
  labels:
    app.kubernetes.io/part-of: validation-v1
    apps.tanzu.vmware.com/workload-type: web
spec:
  params:
    - name: debug
      value: "false"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
  source:
    git:
      url: https://github.com/metaage-vmware/validation.git
      ref:
        branch: master
